### ISSUE TITLE
Account registration box offset

### ISSUE THREAD

**Issue by aerovolts** [ArdaCraft/IssueTracker#31]
When creating an account on the new Discourse forums the registration box is offset to the right had side of the screen.

Perhaps this is caused by the custom dropdown menu that was added?

[Screenshot](http://i.imgur.com/2W1Gi1Z.png)

**Comment by aerovolts** [comment]
This also occurs on the user information boxes that appear when you click on someone's username.

**Comment by dags-** [comment]
It was actually the css that changes the background colour of the main div - it was setting different widths/adjusting margins/paddings etc:
```css
#main {
  width: 1125px;
  min-height: 500px;
  background-color: #FAFAFA;
  margin: 0 auto;
  padding: 0 25px 25px;
 }
```

I found a different way to achieve the same look (I think):

```css
#main-outlet {
  background-color:#FAFAFA;
}
```
